package despacho.ws.servicios.consumidos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-01T17:58:18.732-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://portalEstadoEntrega/", name = "ServidorEstadoEntregaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface ServidorEstadoEntregaBean {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "notificarEntregaDespacho", targetNamespace = "http://portalEstadoEntrega/", className = "despacho.ws.servicios.consumidos.NotificarEntregaDespacho")
    @WebMethod
    @ResponseWrapper(localName = "notificarEntregaDespachoResponse", targetNamespace = "http://portalEstadoEntrega/", className = "despacho.ws.servicios.consumidos.NotificarEntregaDespachoResponse")
    public java.lang.String notificarEntregaDespacho(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
