package despacho.ws.servicios.expuestos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-01T16:46:31.631-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "OrdenDespachoSoapWSBeanService", 
                  wsdlLocation = "file:/home/neco/dev/wjb/icr_des_rest/wsdl/OrdenDespachoSoapWSBean.wsdl",
                  targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/") 
public class OrdenDespachoSoapWSBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.interfaces.tpo.ia.fain.uade/", "OrdenDespachoSoapWSBeanService");
    public final static QName OrdenDespachoSoapWSBeanPort = new QName("http://soap.interfaces.tpo.ia.fain.uade/", "OrdenDespachoSoapWSBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/neco/dev/wjb/icr_des_rest/wsdl/OrdenDespachoSoapWSBean.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrdenDespachoSoapWSBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/neco/dev/wjb/icr_des_rest/wsdl/OrdenDespachoSoapWSBean.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrdenDespachoSoapWSBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrdenDespachoSoapWSBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrdenDespachoSoapWSBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrdenDespachoSoapWSBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrdenDespachoSoapWSBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrdenDespachoSoapWSBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrdenDespachoSoapWS
     */
    @WebEndpoint(name = "OrdenDespachoSoapWSBeanPort")
    public OrdenDespachoSoapWS getOrdenDespachoSoapWSBeanPort() {
        return super.getPort(OrdenDespachoSoapWSBeanPort, OrdenDespachoSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrdenDespachoSoapWS
     */
    @WebEndpoint(name = "OrdenDespachoSoapWSBeanPort")
    public OrdenDespachoSoapWS getOrdenDespachoSoapWSBeanPort(WebServiceFeature... features) {
        return super.getPort(OrdenDespachoSoapWSBeanPort, OrdenDespachoSoapWS.class, features);
    }

}
