package despacho.ws.servicios.expuestos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-01T16:46:31.586-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", name = "OrdenDespachoSoapWS")
@XmlSeeAlso({ObjectFactory.class})
public interface OrdenDespachoSoapWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recibirOrdenDespacho", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", className = "despacho.ws.servicios.expuestos.RecibirOrdenDespacho")
    @WebMethod
    @ResponseWrapper(localName = "recibirOrdenDespachoResponse", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", className = "despacho.ws.servicios.expuestos.RecibirOrdenDespachoResponse")
    public despacho.ws.servicios.expuestos.Resultado recibirOrdenDespacho(
        @WebParam(name = "arg0", targetNamespace = "")
        despacho.ws.servicios.expuestos.OrdenDespacho arg0
    ) throws ArticuloDesconocidoException_Exception, OrdenDespachoYaExisteException_Exception, Exception_Exception;
}
